### ISSUE TITLE
Basic questions from a new user

### ISSUE THREAD

**Issue by zhihengw** [opensha/opensha-apps#14]
Hi, I am new to OpenSHA and have followed the tutorial to finish some cases. Then I get a few questions that I would like to ask:
1. In the calculation type, what is the difference between probabilistic and deterministic in terms of the algorithms?
2. If I only want to work on one hazard model and change the values of model parameters in each simulation, should I choose "deterministic" and select a specific model from the "Set IMR" and "Eqk Rup Forecast" lists, then manually modify the parameter values to run each simulation?
3. Is it possible to work on a script-based model so that batch processing is applicable?

Thanks a lot!

**Comment by kevinmilner** [comment]
Replied to the [issue opened in the new consolidated repository](https://github.com/opensha/opensha/issues/23)
