### ISSUE TITLE
Possible Error in "Attenuation Relationship Plotter (Version: 1.5.0)"

### ISSUE THREAD

**Issue by shkma** [opensha/opensha-apps#5]
I used "Attenuation Relationship Plotter (Version: 1.5.0)."
I generated a plot of relationship between "median" and "SA Period" using "Boore & Atkinson (2008)" attenuation model.
Then I saw that the value "pga4nl" was not computed properly from the OpenSHA.
I found that this was because the OpenSHA uses "R_ref=1.0(km)" for pga4nl instead of using "R_ref=5.0(km)."
Based on the figure legend of Table 6 in Boore and Atkinson (2008), "R_ref=5.0(km)" should be used for computation of "pga4nl."
This change will change the spectral acceleration at short period range (T<0.75second).
---
Reference (please see the legend of Table 6 in the following article):
Boore DM, Atkinson GM. (2008). "Ground-Motion Prediction Equations for the Average Horizontal Component of PGA, PGV, and 5%-Damped PSA at Spectral Periods between 0.01 s and 10.0 s." Earthquake Spectra. Volume: 24, Issue: 1, Pages: 99-138. https://doi.org/10.1193/1.2830434

![Screenshot_BA08_1](https://user-images.githubusercontent.com/30915935/89128819-5bfad600-d4c6-11ea-89f4-b39024ebb3fd.JPG)
![Screenshot_BA08_2](https://user-images.githubusercontent.com/30915935/89128820-5bfad600-d4c6-11ea-8e3d-fd7fb689fb79.JPG)
![Capture](https://user-images.githubusercontent.com/30915935/89138897-1a404e80-d50b-11ea-929c-18ee7564d9ce.JPG)

**Comment by kevinmilner** [comment]
Good catch and thanks for the report. I'm not quite sure how this snuck through our test cases, but looking at our code, the paper, and their original fortran input files I think you're right. @field-usgs, did you implement this model? Any thoughts?

**Comment by pmpowers-usgs** [comment]
http://www.daveboore.com/pubs_online.html

Scroll down to the BA08 listing...
_ERRATUM: 27 August 2008. Tom Blake pointed out that the caption to Table 6 should read "Distance-scaling coefficients (Mref=4.5 and Rref=1.0 km for all periods)"._

The guidance in the table 6 caption of the March 2008 EQS manuscript cited in the issue was likely a hold over from the BA07 relation (PEER report(?) and preliminary model) wherein the nonlinear site term had its own coefficients.

**Comment by shkma** [comment]
Thank you both for your response!

@kevinmilner : I implemented the BA08 in Excel and then when I checked my results with the results from OpenSHA, I noticed that OpenSHA uses Rref=1.0 km for all periods including computing pga4nl. Other researchers also used Rref=1.0 for pga4nl, so I was wondering why (ex. https://web.stanford.edu/~bakerjw/GMPEs.html).
@pmpowers-usgs : I checked the BA08 listing. The note added in 27 August 2008 was the last one on pga4nl so I think Rref=1.0 km should be used also for all cases including computing pga4nl. So the OpenSHA is right.

**Comment by kevinmilner** [comment]
Thanks for digging up that errata @pmpowers-usgs, and thanks much for the report @shkma. We can use as many eyes on the code and comparisons as we can get.

I have added a note in the class comments (in opensha-core) referencing where that value came from, closing this issue now.
