### ISSUE TITLE
Issues with Using OpenSHA to Extract Ground Motions Medians and Stds

### ISSUE THREAD

**Issue by wangcb98** [opensha/opensha-apps#9]
Hi I am a graduate student at Stanford. I was attempting to utilize OpenSHA java application to get the ground motion intensity data, which worked perfectly well in the past, but encountered problems since about last July. I am writing to inquiry whether there has been an update or whether you depreciated the ERF. A couple of students and researchers here at Stanford have encountered similar issues. My email address is wangcb@stanford.edu. Thank you for your time.

**Comment by kevinmilner** [comment]
Hello @wangcb98, are you using the most recent version of our applications page? They can be found at the "releases" page of this repository, or there's more information at https://opensha.org/Applications

If you are running the current version and run into any issues, please paste the error stack trace as a comment (it will print to the console, or also should bring up a bug report dialog that can automatically populate a new ticket for you). It will look some thing like (this is an example from another ticket):

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at org.opensha.sha.gui.HazardCurveApplication.handleForecastList(HazardCurveApplication.java:1624)
	at org.opensha.sha.gui.HazardCurveApplication.computeHazardCurve(HazardCurveApplication.java:1233)
	at org.opensha.sha.gui.HazardCurveApplication.run(HazardCurveApplication.java:880)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by kevinmilner** [comment]
Closing this as we have not heard back and I'm going to assume it was an issue with an outdated app version. Please reopen and supply error messages if you still need assistance.
